# ===============================================================================================================#
# Copyright 2024 Infosys Ltd.                                                                                    #
# Use of this source code is governed by Apache License Version 2.0 that can be found in the LICENSE file or at  #
# http://www.apache.org/licenses/                                                                                #
# ===============================================================================================================#

[logDetails]
LOG_LEVEL=DEBUG
FILE_NAME=utility_service_log
VERBOSE=False
LOG_DIR=../logs
